/*
 * Copyright (C) 2017 Alberto Bausá Cano
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package app.view_controller;

import app.common.Application;
import app.common.Utils;
import app.common.enums.UserRoleEnum;
import app.model.LoginModel;

/**
 * Pantalla de inicio de sesión.
 *
 * @author Alberto Bausá Cano
 */
public class LoginVC extends library.JIASimpleDialog {
    
    private LoginModel model = new LoginModel();

    /**
     * Creates new form LoginVC
     */
    public LoginVC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        pfPass = new javax.swing.JPasswordField();
        lbImage = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(420, 120));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("<html><b>Por favor, introduzca su usuario y contraseña</b></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 20);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 10, 5);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        add(jLabel3, gridBagConstraints);

        tfUser.setMinimumSize(new java.awt.Dimension(20, 20));
        tfUser.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 10, 20);
        add(tfUser, gridBagConstraints);

        pfPass.setMinimumSize(new java.awt.Dimension(20, 20));
        pfPass.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 20);
        add(pfPass, gridBagConstraints);

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 15);
        add(lbImage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean validateThis() {
        // valida que el usuario esté registrado, y que la contraseña esté vacía
        return Application.db.getRegisteredUsers().containsKey(tfUser.getText())
                        && !Utils.validateString(new String(pfPass.getPassword()));
    }

    @Override
    public void saveThis() {
        // guarda los datos de los componentes en el modelo
        this.model.setUser(tfUser.getText());
        this.model.setPassword(new String(pfPass.getPassword()));
        
        // y setea el rol actual en la base de datos
        Application.db.setCurrentRole(
            model.getUser().equals(UserRoleEnum.Facultativo.name()) ? UserRoleEnum.Facultativo
                : model.getUser().equals(UserRoleEnum.Triaje.name()) ? UserRoleEnum.Triaje : UserRoleEnum.Desconocido);
    }

    @Override
    public void cleanThis() {
        // limpia el diálogo
        Utils.clearDialog(this);
    }

    @Override
    public void getExternVal(String id, Object value) { }

    public LoginModel getModel() {
        return model;
    }

    public void setModel(LoginModel model) {
        this.model = model;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbImage;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}