/*
 * Copyright (C) 2017 Alberto Bausá Cano
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package app.view_controller.menuprincipal;

/**
 *
 * @author Alberto Bausá Cano
 */
public class FichaPacienteVC extends library.JIATreeViewDialog {

    /**
     * Creates new form FichaPacienteVC
     */
    public FichaPacienteVC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();

        setCardPane(jPanel1);
        setPreferredSize(new java.awt.Dimension(400, 306));
        setSplitPane(jSplitPane1);
        setTreeView(jTree1);
        setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setContinuousLayout(true);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 0));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("(default)");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setRowHeight(23);
        jTree1.setSelectionModel(setSelectionMode());
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanel1.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jSplitPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        Object[] nodesPath = evt.getPath().getPath();
        ((java.awt.CardLayout) jPanel1.getLayout()).show(jPanel1, nodesPath[nodesPath.length - 1].toString());
    }//GEN-LAST:event_jTree1ValueChanged
    
    @Override
    public boolean validateThis() { return true; } // nada que validar

    @Override
    public void saveThis() { } // nada que guardar

    @Override
    public void cleanThis() { }
    /**
     * Permite establecer el modelo de selección como 'individual' para la vista de árbol.
     *
     * @return El modelo de selección para el árbol
     */
    private javax.swing.tree.TreeSelectionModel setSelectionMode() {
        
        javax.swing.tree.TreeSelectionModel selectionModel = jTree1.getSelectionModel();
        selectionModel.setSelectionMode(javax.swing.tree.TreeSelectionModel.SINGLE_TREE_SELECTION);
        return selectionModel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
